# Necessary Libraries

In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


# Scaler and Built In Functions

In [2]:
# Sample scalar and array inputs
scalar = 3.7
arr = np.array([33, 44, 55, 66, 77, 88])

# Trigonometric functions
sin_values = np.sin(arr)
cos_values = np.cos(arr)
tan_values = np.tan(arr)
asin_values = np.arcsin(np.clip(arr / np.max(arr), -1, 1))  # Normalized and Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(arr / np.max(arr), -1, 1))
atan_values = np.arctan(arr)

# Exponential and logarithm
exp_values = np.exp(arr)
log_values = np.log(arr)  # Natural logarithm

# Absolute value and square root
abs_values = np.abs(arr)
sqrt_values = np.sqrt(arr)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(arr, 2)

# Rounding functions
round_values = np.round(arr)
floor_values = np.floor(arr)
ceil_values = np.ceil(arr)

# Display results
print("sin:", sin_values)
print("cos:", cos_values)
print("tan:", tan_values)
print("asin:", asin_values)
print("acos:", acos_values)
print("atan:", atan_values)
print("exp:", exp_values)
print("log:", log_values)
print("abs:", abs_values)
print("sqrt:", sqrt_values)
print("rem:", rem_values)
print("round:", round_values)
print("floor:", floor_values)
print("ceil:", ceil_values)

sin: [ 0.99991186  0.01770193 -0.99975517 -0.02655115  0.99952016  0.0353983 ]
cos: [-0.01327675  0.99984331  0.02212676 -0.99964746 -0.03097503  0.99937328]
tan: [-7.53130148e+01  1.77046993e-02 -4.51830879e+01  2.65605178e-02
 -3.22685758e+01  3.54205013e-02]
asin: [0.38439677 0.52359878 0.67513153 0.84806208 1.06543582 1.57079633]
acos: [1.18639955 1.04719755 0.89566479 0.72273425 0.50536051 0.        ]
atan: [1.54050257 1.54807297 1.55261651 1.55564597 1.55781004 1.55943318]
exp: [2.14643580e+14 1.28516001e+19 7.69478527e+23 4.60718663e+28
 2.75851345e+33 1.65163625e+38]
log: [3.49650756 3.78418963 4.00733319 4.18965474 4.34380542 4.47733681]
abs: [33 44 55 66 77 88]
sqrt: [5.74456265 6.63324958 7.41619849 8.1240384  8.77496439 9.38083152]
rem: [1 0 1 0 1 0]
round: [33 44 55 66 77 88]
floor: [33. 44. 55. 66. 77. 88.]
ceil: [33. 44. 55. 66. 77. 88.]


## Do it For 2X2 matrix

In [ ]:
# Creating a 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)


Matrix:
 [[1 2]
 [3 4]]

sin:
 [[ 0.84147098  0.90929743]
 [ 0.14112001 -0.7568025 ]]

cos:
 [[ 0.54030231 -0.41614684]
 [-0.9899925  -0.65364362]]

tan:
 [[ 1.55740772 -2.18503986]
 [-0.14254654  1.15782128]]

asine:
 [[0.25268026 0.52359878]
 [0.84806208 1.57079633]]

acosine:
 [[1.31811607 1.04719755]
 [0.72273425 0.        ]]

atangent:
 [[0.78539816 1.10714872]
 [1.24904577 1.32581766]]

exp:
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]

log (natural):
 [[0.         0.69314718]
 [1.09861229 1.38629436]]

abs:
 [[1 2]
 [3 4]]

sqrt:
 [[1.         1.41421356]
 [1.73205081 2.        ]]

rem (remainder when divided by 2):
 [[1 0]
 [1 0]]

round:
 [[1 2]
 [3 4]]

floor:
 [[1. 2.]
 [3. 4.]]

ceil:
 [[1. 2.]
 [3. 4.]]


### To Students: Do the same for 3*2 matrix

In [3]:
# Creating a 3x2 matrix
matrix = np.array([[22, 15], [33, 24], [50, 10]])

# Trigonometric functions
sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))  # Clipping for valid range [-1, 1]
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

# Exponential and logarithm
exp_values = np.exp(matrix)
log_values = np.log(matrix)  # Natural logarithm (log base e)

# Absolute value and square root
abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

# Remainder when divided by a scalar (e.g., 2)
rem_values = np.remainder(matrix, 2)

# Rounding functions
round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

# Display results
print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[22 15]
 [33 24]
 [50 10]]

sin:
 [[-0.00885131  0.65028784]
 [ 0.99991186 -0.90557836]
 [-0.26237485 -0.54402111]]

cos:
 [[-0.99996083 -0.75968791]
 [-0.01327675  0.42417901]
 [ 0.96496603 -0.83907153]]

tan:
 [[ 8.85165604e-03 -8.55993401e-01]
 [-7.53130148e+01 -2.13489670e+00]
 [-2.71900612e-01  6.48360827e-01]]

asine:
 [[0.45559867 0.30469265]
 [0.72081876 0.50065471]
 [1.57079633 0.20135792]]

acosine:
 [[1.11519765 1.26610367]
 [0.84997757 1.07014161]
 [0.         1.36943841]]

atangent:
 [[1.52537305 1.50422816]
 [1.54050257 1.52915375]
 [1.55079899 1.47112767]]

exp:
 [[3.58491285e+09 3.26901737e+06]
 [2.14643580e+14 2.64891221e+10]
 [5.18470553e+21 2.20264658e+04]]

log (natural):
 [[3.09104245 2.7080502 ]
 [3.49650756 3.17805383]
 [3.91202301 2.30258509]]

abs:
 [[22 15]
 [33 24]
 [50 10]]

sqrt:
 [[4.69041576 3.87298335]
 [5.74456265 4.89897949]
 [7.07106781 3.16227766]]

rem (remainder when divided by 2):
 [[0 1]
 [1 0]
 [0 0]]

round:
 [[22 15]
 [33 24]
 [50 10

# Vector Functions

In [ ]:
# Sample vector (1D array)
vec = np.array([3, 1, 4, 1, 5, 9, 2, 6])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in ascending order
sorted_vec = np.sort(vec)



# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted vector:", sorted_vec)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 9 at index 5
Min value: 1 at index 1
Length of vector: 8
Sorted vector: [1 1 2 3 4 5 6 9]
Sum of elements: 31
Product of elements: 6480
Median value: 3.5
Mean value: 3.875
Standard deviation: 2.5708704751503917


### To Students: Do the same for 2*3 matrix, what about descending sort within rows or in total matrix? What about using floating numbers?

In [7]:
# Sample vector (1D array)
vec = np.array([[55.1, 45.5, 65.3], [85.6, 35.9, 75.2]])

# 1. Maximum value and index of max element
max_value = np.max(vec)
max_index = np.argmax(vec)  # Index of max element

# 2. Minimum value and index of min element
min_value = np.min(vec)
min_index = np.argmin(vec)  # Index of min element

# 3. Length of the vector
vec_length = len(vec)  # Equivalent to MATLAB's length()

# 4. Sorting in descending order(row)
row_des = np.array([sorted(row, reverse = True) for row in vec])


flat = vec.flatten()
entire_des = np.array((sorted(flat, reverse = True)))




# 5. Sum of elements
sum_values = np.sum(vec)

# 6. Product of elements
prod_values = np.prod(vec)

# 7. Median value
median_value = np.median(vec)

# 8. Mean value
mean_value = np.mean(vec)

# 9. Standard deviation
std_dev = np.std(vec)

# Display results
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Length of vector:", vec_length)
print("Sorted row vector:", row_des)
print("Entire descending:", entire_des)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Max value: 85.6 at index 3
Min value: 35.9 at index 4
Length of vector: 2
Sorted row vector: [[65.3 55.1 45.5]
 [85.6 75.2 35.9]]
Entire descending: [[85.6 75.2 65.3 55.1 45.5 35.9]]
Sum of elements: 362.59999999999997
Product of elements: 37832255204.48192
Median value: 60.2
Mean value: 60.43333333333333
Standard deviation: 16.97269048272024
